### ISSUE TITLE
Native oauth2 authentication for gmail accounts

### ISSUE THREAD

**Issue by JonnyMako** [muttmua/mutt#1]
This is a feature request for building native oauth2 authentication into mutt for use with gmail accounts.

Backstory:

Google has a python script that does this and mutt users have been using this to access their gmail accounts:

https://github.com/google/gmail-oauth2-tools/blob/master/python/oauth2.py

However, this script isn't being maintained and hasn't been working with python 3 for a while. Now coming to present, a recent update to openssl broke this script. OpenSSL guys relented and reverted the change for this version, but come version 3 of OpenSSL, google's oauth2.py will finally die for good. This is a good time to start thinking about baking oauth2 into mutt. I've added a similar comment to neomutt, but it would be nice if this was done upstream in mutt natively.

Relevant issues:
openssl/openssl#11381
google/gmail-oauth2-tools#21

**Comment by evxn** [comment]
@JonnyMako I believe you will find no answers here. You're talking to a mirror. The project is developed on gitlab. The link is in the repository description in the <> Code section.

**Comment by JonnyMako** [comment]
@evxn thanks! I've opened the issue on gitlab.
